[package]
name = "beacon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
<<<<<<< HEAD
hyper = "1.0.0-rc.1"
chrono = "0.4.22"

beacon-controller = { path = "../beacon-controller"}
=======
chrono = "0.4.22"
>>>>>>> origin/luco/fix
